// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-74Qo69G8gQBc-mZTvest8uce6EkuIr0',
    appId: '1:1028472675433:web:6d539eaaf878c3561d56f8',
    messagingSenderId: '1028472675433',
    projectId: 'flutterfirebase-d86fe',
    authDomain: 'flutterfirebase-d86fe.firebaseapp.com',
    storageBucket: 'flutterfirebase-d86fe.appspot.com',
    measurementId: 'G-TZN4QL0G1W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc5mLGt_WApv-8HdNyteAThkM-IX1rl4Q',
    appId: '1:1028472675433:android:7116cae646380da01d56f8',
    messagingSenderId: '1028472675433',
    projectId: 'flutterfirebase-d86fe',
    storageBucket: 'flutterfirebase-d86fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8MjPK9A9dGoyGa5TwsVuoCoq7XEpUwSg',
    appId: '1:1028472675433:ios:1fd3ada77976adde1d56f8',
    messagingSenderId: '1028472675433',
    projectId: 'flutterfirebase-d86fe',
    storageBucket: 'flutterfirebase-d86fe.appspot.com',
    iosClientId: '1028472675433-2g1phcir8ebkfv90rp726ahj13cj3ceu.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasetutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8MjPK9A9dGoyGa5TwsVuoCoq7XEpUwSg',
    appId: '1:1028472675433:ios:1fd3ada77976adde1d56f8',
    messagingSenderId: '1028472675433',
    projectId: 'flutterfirebase-d86fe',
    storageBucket: 'flutterfirebase-d86fe.appspot.com',
    iosClientId: '1028472675433-2g1phcir8ebkfv90rp726ahj13cj3ceu.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebasetutorial',
  );
}
